apiVersion: apps/v1
kind: Deployment
metadata:
  name: bombermonster-deployment # Name of deployments and pods
spec:
  replicas: 3 # name of pods replicas
  selector:
    matchLabels:
      app: bombermonster # name of label(template) that it will replicate
  template:
    metadata:
      labels:
        app: bombermonster # label name
    spec:
      containers:
        - name: bombermonster
          image: cardoso010/bombermonster:latest # Image name (nginx, caddy)
          ports:
            - containerPort: 80
